version: "3.5"

volumes:
    postgres_data:
        driver: local
    redis_data:
        driver: local

services:
    redis:
        restart: always
        image: redis:6.2.3
        volumes:
            - redis_data:/data
        ports:
            - 6379:6379
        networks:
            - default

    postgres:
        restart: always
        build:
            context: ./docker/postgres
            dockerfile: ./Dockerfile
        environment:
            TZ: ${TZ}
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        networks:
            - default
    php:
        restart: always
        build:
            context: ./docker/php
            dockerfile: ./Dockerfile
        environment:
            TZ: ${TZ}
            UID: ${UID}
        volumes:
            - ./:/var/www/html
        depends_on:
            - redis
            - postgres
        ports:
            - 9000:9000
        networks:
            - default

    nginx:
        restart: always
        build:
            context: ./docker/nginx
            dockerfile: ./Dockerfile
        environment:
            TZ: ${TZ}
            UID: ${UID}
        volumes:
            - ./:/var/www/html
        depends_on:
            - php
        ports:
            - 80:80
            - 6001:6001
        networks:
            - default

networks:
    default:
